### ISSUE TITLE
scale=4, patch_size=192 will make my GPU(Tesla V100, 32G) exploded

### ISSUE THREAD

**Issue by conson0214** [SHI-Labs/Cross-Scale-Non-Local-Attention#1]
我使用的是Tesla V100 显存32G
当训练scale=4的模型时, patch_size=192, 显存会提示不足, 其他参数与Example command中一致
尝试减少了depth也不行
想问一下你们是如何训练x4模型的?

**Comment by HarukiYqM** [comment]
> 我使用的是Tesla V100 显存32G
> 当训练scale=4的模型时, patch_size=192, 显存会提示不足, 其他参数与Example command中一致
> 尝试减少了depth也不行
> 想问一下你们是如何训练x4模型的?

您好，
我们训练的时候使用了4卡V100。因为CS-NL Attention会将尺度放大到HR size 所以patchsize对显存影响比较大。如果显存不足，可以使用这个setting：patchsize= 120/128，batch size=12，也可以reproduce结果。

**Comment by conson0214** [comment]
多谢~按照你给的参数已经解决了

**Comment by Ralapfranco** [comment]
> 多谢~按照你给的参数已经解决了

can you help me?
![image](https://user-images.githubusercontent.com/93692234/176076330-9dadc3e1-ebe8-4792-af61-a5c5dd95a34c.png)

**Comment by Ralapfranco** [comment]
> > 我使用的是Tesla V100 显存32G
> > 当训练scale=4的模型时, patch_size=192, 显存会提示不足, 其他参数与Example command中一致
> > 尝试减少了depth也不行
> > 想问一下你们是如何训练x4模型的?
> 
> 您好， 我们训练的时候使用了4卡V100。因为CS-NL Attention会将尺度放大到HR size 所以patchsize对显存影响比较大。如果显存不足，可以使用这个setting：patchsize= 120/128，batch size=12，也可以reproduce结果。

can you help me？
![1656385879442](https://user-images.githubusercontent.com/93692234/176083970-46e7a255-4034-4a39-8ed6-6dff20817379.png)
 if i dont set batch size=12 ， i should how to set parameters to reproduce result of x4model
