### ISSUE TITLE
runtimeError

### ISSUE THREAD

**Issue by all-a-b-c** [SHI-Labs/Cross-Scale-Non-Local-Attention#11]
yi = F.conv_transpose2d(yi, wi_center, stride=self.stride * self.scale, padding=self.scale)
RuntimeError: Given transposed=1, weight of size 1632 128 6 6, expected input[1, 1584, 96, 67] to have 1632 channels, but got 1584 channels instead

python3 main.py --chop --model CSNLN --scale 2 --patch_size 96 --save CSNLN_x2 --n_feats 128 --depth 5 --n_GPUs 2 
do you know how to deal with it

**Comment by all-a-b-c** [comment]
the default train_data is DIV2K  test_data is Set5
it occurs int the process of evaluation

**Comment by HarukiYqM** [comment]
> the default train_data is DIV2K test_data is Set5
> it occurs int the process of evaluation

Can you test properly on Set5?

**Comment by all-a-b-c** [comment]
> > the default train_data is DIV2K test_data is Set5
> > it occurs int the process of evaluation
> 
> Can you test properly on Set5?

No  the problem occurs in the process of evaluation after the first epoch when I train the model

**Comment by HarukiYqM** [comment]
> > > the default train_data is DIV2K test_data is Set5
> > > it occurs int the process of evaluation
> > 
> > 
> > Can you test properly on Set5?
> 
> No the problem occurs in the process of evaluation after the first epoch when I train the model

Hi, did you use the latest code from this repo? Everything works well on my computer.
<img width="568" alt="Screen Shot 2020-07-25 at 7 25 15 PM" src="https://user-images.githubusercontent.com/30628038/88456314-390d6800-ceaf-11ea-96e2-6968a0a0cd8f.png">
<img width="563" alt="Screen Shot 2020-07-25 at 7 42 34 PM" src="https://user-images.githubusercontent.com/30628038/88456330-61956200-ceaf-11ea-8724-fbfa1f206443.png">

**Comment by all-a-b-c** [comment]
> > > > the default train_data is DIV2K test_data is Set5
> > > > it occurs int the process of evaluation
> > > 
> > > 
> > > Can you test properly on Set5?
> > 
> > 
> > No the problem occurs in the process of evaluation after the first epoch when I train the model
> 
> Hi, did you use the latest code from this repo? Everything works well on my computer.
> <img alt="Screen Shot 2020-07-25 at 7 25 15 PM" width="568" src="https://user-images.githubusercontent.com/30628038/88456314-390d6800-ceaf-11ea-96e2-6968a0a0cd8f.png">
> <img alt="Screen Shot 2020-07-25 at 7 42 34 PM" width="563" src="https://user-images.githubusercontent.com/30628038/88456330-61956200-ceaf-11ea-8724-fbfa1f206443.png">

。。you're right   there is something wrong in forward_chop function   thank you very much
