### ISSUE TITLE
Inference speed problem

### ISSUE THREAD

**Issue by lxy5513** [SHI-Labs/Cross-Scale-Non-Local-Attention#13]
Thanks for great work, I train model on my own dataset, In inference mode, The speed is some little weird, about 6s/per picture

The model weight only 12MB, why inference speed is slow, Would you mind give me some advice, Thanks in advance.

**Comment by HarukiYqM** [comment]
Hi, I am not sure what causes this problem. The inference speed depends on your devices and the size of images. For the model itself, recurrently computing attention also slow down the speed.

**Comment by lxy5513** [comment]
Thanks for your reponse, my device is Tesla P40, and my input image shape is 265X192

**Comment by lxy5513** [comment]
Could you mind tell your device, the size of image and inference speed ?

**Comment by HarukiYqM** [comment]
> Could you mind tell your device, the size of image and inference speed ?

Since currently I am in travel, I cannot access to GPUs. I roughly remembered that testing the model on gtx1080 takes around 1 FPS on Set5. If your device have enough memory, you may also want to have a look at chop_forward in model/_init_.py to speed up.

**Comment by lxy5513** [comment]
Thanks, I will try your advice, thank you.
