### ISSUE TITLE
How much memory does it require?

### ISSUE THREAD

**Issue by aryan-f** [SHI-Labs/Cross-Scale-Non-Local-Attention#14]
I'm unable to train the model with the default config (`n_feats`: 128, `depth`: 12) on a new dataset (with images slightly larger than DIV2K) even with a batch size of 1! Do I have the cut down the images? 
I'm using a T4 card with 16GB of memory, accompanied by 128GB of RAM.

**Comment by HarukiYqM** [comment]
Hi, what is your patch size and did you follow the training command? I trained my x2 model on a single V100 16G.

**Comment by aryan-f** [comment]
Oh yeah. I've already trained X2 and X3 with no problem. I face this issue with X4. Here's the exact comment I'm using:
```
python main.py --model CSNLN --dir_data ../../../data --data_train Draper --data_test Draper --data_range 1-350,1-10 --chop --ext img --scale 4 --patch_size 192  --n_feats 96 --depth 12 --epochs 150 --batch_size 1  --save X4 --print_every 1
```
I wasn't able to quite understand how the code works, so I was wondering if you could help. What exactly happens in every epoch regarding the images? Does the model read each image in the training set, chop it up to non-overlapping patches of the specified size, and use all patches in every epoch? Or does it select a random patch from each image in the training set in every epoch, as RCAN does?

**Comment by HarukiYqM** [comment]
> Oh yeah. I've already trained X2 and X3 with no problem. I face this issue with X4. Here's the exact comment I'm using:
> 
> ```
> python main.py --model CSNLN --dir_data ../../../data --data_train Draper --data_test Draper --data_range 1-350,1-10 --chop --ext img --scale 4 --patch_size 192  --n_feats 96 --depth 12 --epochs 150 --batch_size 1  --save X4 --print_every 1
> ```
> 
> I wasn't able to quite understand how the code works, so I was wondering if you could help. What exactly happens in every epoch regarding the images? Does the model read each image in the training set, chop it up to non-overlapping patches of the specified size, and use all patches in every epoch? Or does it select a random patch from each image in the training set in every epoch, as RCAN does?

Hi, to deal with memory issue, you can simply reduce patch size to 120/128. We trained a model in this case and find it will also reproduce the results. This code will select a random patch like RCAN does.

**Comment by aryan-f** [comment]
Oh, if it doesn't reduce the performance of the model, great!
Really? Because when I ran RCAN, the code logged 350 iterations for the training phase (the same number as the training images), but CSNLN shows something around 5000. The training phase also goes on far longer than RCAN, which was weird, since the model has so many fewer weights compared to RCAN.

**Comment by HarukiYqM** [comment]
> Oh, if it doesn't reduce the performance of the model, great!
> Really? Because when I ran RCAN, the code logged 350 iterations for the training phase (the same number as the training images), but CSNLN shows something around 5000. The training phase also goes on far longer than RCAN, which was weird, since the model has so many fewer weights compared to RCAN.

Hi, you can find the patch generation code in data/common.py: get_patch. The reason for slow maybe due to that the model contains several rounds of self-attention, which increase computation complexity.

**Comment by aryan-f** [comment]
Gotcha. Really appreciate the help.
