### ISSUE TITLE
IS-NL module

### ISSUE THREAD

**Issue by duanxuesong** [SHI-Labs/Cross-Scale-Non-Local-Attention#16]
The paper mentioned that the IS-NL module is region-based. But I read the NonLocalAttention part, and did not find the corresponding codes.

**Comment by WOWspring** [comment]
I have the same question. Actually, I'm confused why the output feature map from IS-NL module is SW * SH. I think the size of the output should be W * H...

**Comment by HarukiYqM** [comment]
> The paper mentioned that the IS-NL module is region-based. But I read the NonLocalAttention part, and did not find the corresponding codes.

Sorry for late reply. We follow the SAN by dividing the input image into regions during inference. Please check chop_forward function at model/__init__.py for reference.
