### ISSUE TITLE
how does the model downscale when image size is not divisible?

### ISSUE THREAD

**Issue by seaside-tech** [SHI-Labs/Cross-Scale-Non-Local-Attention#18]
As mentioned above, I can't see from the code how to, for example, downscale a 31*31 by a x2 scale and then upscale it to the same size, could you kindly teach me about it? Just in case that LR image can't be downscaled

**Comment by HarukiYqM** [comment]
> As mentioned above, I can't see from the code how to, for example, downscale a 31*31 by a x2 scale and then upscale it to the same size, could you kindly teach me about it? Just in case that LR image can't be downscaled

Sorry for late reply. At training time, we use the 48 x48 patches as input, so you basically don't do anything. At inference time, you can simply pad the input so that they can be divided by any scale factor. Please check the chop_forward function at model/__init__.py for reference.
