### ISSUE TITLE
Attention Map

### ISSUE THREAD

**Issue by codyshen0000** [SHI-Labs/Cross-Scale-Non-Local-Attention#26]
Hi ! Could you please share with me how to visualize the attention feature map?  Thanks!

**Comment by HarukiYqM** [comment]
Hi, you can take this code from CCNet as reference: https://github.com/speedinghzl/CCNet/issues/3

**Comment by nanmehta** [comment]
could anyone please help me. that whether I have to write this code in the training code or te inference code
