### ISSUE TITLE
about code

### ISSUE THREAD

**Issue by liuweiyy** [SHI-Labs/Cross-Scale-Non-Local-Attention#3]
I cannot understand why yi = yi / 6 in class CrossScaleAttention(nn.Module),can you explain it to me?thank you

**Comment by HarukiYqM** [comment]
> I cannot understand why yi = yi / 6 in class CrossScaleAttention(nn.Module),can you explain it to me?thank you

Hi,
this constant is just used to normalize the obtained maps. The performance is not sensitive to this constant. Other proper value can also work (e.g., 4, 6, 9).

**Comment by SkyeLu** [comment]
> this constant is used to normalize the obtained maps. For kernel size=6 and stride =2, deconvolution will cause 6 overlaps at each position. In fact, the network is not very sensitive to this parameter.

Hi, I think the number should be 9.

**Comment by HarukiYqM** [comment]
> > this constant is used to normalize the obtained maps. For kernel size=6 and stride =2, deconvolution will cause 6 overlaps at each position. In fact, the network is not very sensitive to this parameter.
> 
> Hi, I think the number should be 9.

![CC86E44F-E62B-4ACB-85FE-3CDC7B5F46A0](https://user-images.githubusercontent.com/30628038/84940297-3716f300-b112-11ea-9a15-06de91bf7f1b.jpeg)
Hi, this figure in 1d case may help.

**Comment by HarukiYqM** [comment]
> > this constant is used to normalize the obtained maps. For kernel size=6 and stride =2, deconvolution will cause 6 overlaps at each position. In fact, the network is not very sensitive to this parameter.
> 
> Hi, I think the number should be 9.

Hi, you are corrected. Thank you very much for pointing out. The exact value to average overlapped feature maps should be 9. However, it turns out that the network can easily learn to fit this constant and any proper rescaling factor can work well.
