### ISSUE TITLE
Optimization of cross-scale attention module

### ISSUE THREAD

**Issue by qiqiing** [SHI-Labs/Cross-Scale-Non-Local-Attention#34]
Hello, in your cross-scale module, the patches of the cross-scale feature map are processed as the convolution kernel. The weight parameter of the convolution kernel is fixed, so in the process of backpropagation, this module is optimized What is it? Will the convolution kernel parameters set in F.conv2d and F.conv_transpose2d be optimized?

**Comment by HarukiYqM** [comment]
Those two operators do not have parameters associated with them. The filters of convolution are feature maps which are not directly optimized. But the operation that produced those feature maps are optimized. This is similar to the dynamic conv in some sense.

**Comment by qiqiing** [comment]
> Those two operators do not have parameters associated with them. The filters of convolution are feature maps which are not directly optimized. But the operation that produced those feature maps are optimized. This is similar to the dynamic conv in some sense.

Thank you very much for your reply, I can understand it well. There is another question I want to ask you. During your training, will PSNR basically rise while SSIM fluctuates (decline, increase, decrease, etc.)? Is this normal during training? I removed your "Mutual-Projected Fusion" module. Could it be for this reason?

**Comment by HarukiYqM** [comment]
I think since PSNR is rising it should be normal. Also please ensure there is a local path way when you use CSNLA. You can simply achieve this by adding a residual connection.

**Comment by qiqiing** [comment]
> I think since PSNR is rising it should be normal. Also please ensure there is a local path way when you use CSNLA. You can simply achieve this by adding a residual connection.

alright, thank you very much
