### ISSUE TITLE
Test model_x2.pt

### ISSUE THREAD

**Issue by gong-lei** [SHI-Labs/Cross-Scale-Non-Local-Attention#6]
![Screenshot from 2020-06-29 10-21-56](https://user-images.githubusercontent.com/52185252/85966859-8eab3d80-b9f3-11ea-8f8f-e2bb01d006dd.png)
And my experiment/test/results-B100,Set5,Set14,Urban100 are all empty.I was wondering if there was an error in specifying the path.Can you give me some advice.Thanks so much!

**Comment by HarukiYqM** [comment]
Hi, it seems that your path is incorrect. Please set the dir_data in options.py as the path to your benchmark folder. You may also want to check #4

**Comment by Bitliuliu** [comment]
My question is exactly the same as his. I just want to test and put two pictures in the test set. At the same time, I created a folder and changed option.py according to your method in question 6. The result is still like this

**Comment by Ralapfranco** [comment]
> 
so，how do you deal with it？
