### ISSUE TITLE
Test my own dataset

### ISSUE THREAD

**Issue by Lufei-github** [SHI-Labs/Cross-Scale-Non-Local-Attention#7]
I want to test your trained model on my own dataset.My own dataset's index is 00001.png~24996.png,is like your Urban dataset's img001x2.png~img100x2.png.So I'm going to replace your Urban dataset with my own dataset.But I don't know where and how to change the index.Can you give me some guidance?Thanks a lot!

**Comment by HarukiYqM** [comment]
> I want to test your trained model on my own dataset.My own dataset's index is 00001.png~24996.png,is like your Urban dataset's img001x2.png~img100x2.png.So I'm going to replace your Urban dataset with my own dataset.But I don't know where and how to change the index.Can you give me some guidance?Thanks a lot!

Hi, you can easy test the model on your own images by:

1. Create a folder called Demo
2. Put all your images into that folder
3. Set the dir_demo in option.py to the folder
4. Results will be in results-Demo folder

**Comment by Lufei-github** [comment]
It works! One more small question.
After super resolution,the images' name are 00001_x2_SR.png,but I want to delete "_x2_SR", just  keep the "0001.png".So where should I modify the path name?

**Comment by HarukiYqM** [comment]
> It works! One more small question.
> After super resolution,the images' name are 00001_x2_SR.png,but I want to delete "_x2_SR", just keep the "0001.png".So where should I modify the path name?

Hi, you may need to modify this function: https://github.com/SHI-Labs/Cross-Scale-Non-Local-Attention/blob/e12b90614db3aac12f0e307e95fe9594a4b66539/src/utility.py#L148

**Comment by Lufei-github** [comment]
Thanks so much!!!

**Comment by lynshwoo2022** [comment]
> > I want to test your trained model on my own dataset.My own dataset's index is 00001.png~24996.png,is like your Urban dataset's img001x2.png~img100x2.png.So I'm going to replace your Urban dataset with my own dataset.But I don't know where and how to change the index.Can you give me some guidance?Thanks a lot!
> 
> Hi, you can easy test the model on your own images by:
> 
> 1. Create a folder called Demo
> 2. Put all your images into that folder
> 3. Set the dir_demo in option.py to the folder
> 4. Results will be in results-Demo folder

but after changing like this, runnibf demo.sh can't ouput any results.

**Comment by 0-Maxwei-0** [comment]
> > > I want to test your trained model on my own dataset.My own dataset's index is 00001.png~24996.png,is like your Urban dataset's img001x2.png~img100x2.png.So I'm going to replace your Urban dataset with my own dataset.But I don't know where and how to change the index.Can you give me some guidance?Thanks a lot!
> > 
> > 
> > Hi, you can easy test the model on your own images by:
> > 
> > 1. Create a folder called Demo
> > 2. Put all your images into that folder
> > 3. Set the dir_demo in option.py to the folder
> > 4. Results will be in results-Demo folder
> 
> but after changing like this, runnibf demo.sh can't ouput any results.

me too. Have you solved this?
